### ISSUE TITLE
[macOS] Packaged version of CemrgApp does not load DICOMS

### ISSUE THREAD

**Issue by alonsoJASL** [CemrgAppDevelopers/CemrgApp#13]
A full explanation of this bug can be found [in here](https://phabricator.mitk.org/T26451). It is unsure when is this going to be addressed by the MITK team, as they were not able to reproduce our error. 

This issue is then created here to determine the workarounds necessary to load and convert DICOMs external to the DICOM plugins for our users to handle.

**Comment by alonsoJASL** [comment]
### Ideas
**Docker container linked to `CemrgCommandLine` class**  
This would be a docker container with either of the following libraries: 
- [dicom2nifti](https://anaconda.org/conda-forge/dicom2nifti) 
- [c3d](http://www.itksnap.org/pmwiki/pmwiki.php?n=Downloads.SNAP3) 

**Building MITK/CemrgApp with a newer version of DCMTK**
This would be achieved by setting the CMake variable `MITK_EXTERNAL_DCMTK` to a more recent version of DCMTK than hte one currently in MITK v2018.04.2, which might address the problem.

**Comment by OrodRazeghi** [comment]
I put together a Docker container for the dicom2nifti python tool and pushed it to the docker hub. The test on one of the example MRI cases was successful. The syntax to test the code is as follows:
`orodrazeghi/dicom-converter "Dicom Folder" --gantry --inconsistent`
The gantry and inconsistent flags (dicom2nii options) are by default false.
The dicom folder needs to be linked up with the container using the volume parameter. For example:
`docker run --rm --volume=$(pwd):/Data orodrazeghi/dicom-converter "Mri Heart"`
@alonsoJASL if this works on your example cases, we can put this as the backup option for the dicom converter

**Comment by alonsoJASL** [comment]
Made initial tests on branch feature/alternative_dicom_reader. 

**Commit 37778b4:** Lays out the initial changes in the `CemrgCommandLine` class, as well as its implementation in the `AtrialScarView` plugin. 

**Further problems:** 
+ Orientation of the dicoms might need to be addressed. When tried a simple segmentation, the `LA` was not centred at akl. 
+ Also, the implementation in the plugin was made in the `AtrialScarView::ProcessIMGS` method, this could change if there's a need for a cleaner code which can be passed on to other plugins.

**Comment by alonsoJASL** [comment]
**Commits:** 67732e9 and 57ee030 add a feature to reorient the loaded NIFTI file to RAI configuration and resample them as isometric. This functionality has been included in the `CermgCommonUtils` class, so it can be used across all plugins. 

At the moment, this is only true in the `AtrialScarView` plugin. Next stage involves testing with cases where the DICOM conversion is known to be a problem. I'll try to contact the clinicians getting this problem.

**Comment by alonsoJASL** [comment]
Closing issue as it has been finalised. Testing done so far indicates that the alternative DICOM reader works well. This is currently in the Development branch.
