### ISSUE TITLE
Font size resets after closing the App to very small

### ISSUE THREAD

**Issue by driainsim** [CemrgAppDevelopers/CemrgApp#14]
Have to reset font sixe on each opening back up to readable size i.e 14 (default appears to be 9)

**Comment by alonsoJASL** [comment]
This should not happen every time, as CermgAp remembers the previous state in which it was closed. Does this happen in every occasion? 

To fix it, go to preferences, <kbd>Cmd</kbd> + <kbd>,</kbd> on macOS, and under Themes, select the font to `<<system>>`.

**Comment by driainsim** [comment]
Happens every time,

Also doesn’t save the perspective either - default is Motion quantification


Dr Iain Sim

MBBS BSc MRCP
Clinical Research Fellow in Cardiology
School of Biomedical Engineering and Imaging Sciences
King’s College London, 4th Floor, North Wing, St. Thomas’ Hospital

@driainsim
07547019405

On 10 Jul 2020, at 10:17, Jose Alonso Solis-Lemus <notifications@github.com<mailto:notifications@github.com>> wrote:



This should not happen every time, as CermgAp remembers the previous state in which it was closed. Does this happen in every occasion?

To fix it, go to preferences, Cmd + , on macOS, and under Themes, select the font to <<system>>.
