### ISSUE TITLE
Default folder for importing files is awkward

### ISSUE THREAD

**Issue by driainsim** [CemrgAppDevelopers/CemrgApp#15]
Would be great if the default folder location when opening a segmentation or PVclipped.nii was the designated project folder - or a recently used folder- rather than deep inside one of the librarys

**Comment by alonsoJASL** [comment]
When loading data, the initial folder the app defaults to is the one pulled by `mitk::IOUtil::GetProgramPath()`, which corresponds to path where CemrgApp is stored. We are currently testing the showing the pre-selected folder as default, for the case of loading segmentations, we will be expanding this to anyone.

**Comment by alonsoJASL** [comment]
This issue is implemented already for the Scar plugin in commit 37778b4. It needs to be packaged and distributed.
