### ISSUE TITLE
[WathCa] Feature request: Revert to FIND CENTRELINES

### ISSUE THREAD

**Issue by alonsoJASL** [CemrgAppDevelopers/CemrgApp#19]
The following was originally submitted in #17 by @dariadg.

Not an issue but a request:
- After you found centrelines, and displayed clippers
- If you want to change your centrelines, you can’t revert back to find centrelines

Would be great, as can’t always notice if the centreline is going the wrong way. If you want to do it again, have to do
PV clipper again.

**Comment by OrodRazeghi** [comment]
OP's requested feature clashes with resetting clipper planes feature, and therefore will not be implemented at the moment.
