### ISSUE TITLE
[WathCa] Outline full list of commands and buttons

### ISSUE THREAD

**Issue by alonsoJASL** [CemrgAppDevelopers/CemrgApp#20]
This was originally mentioned in #17 by @dariadg 

There are a lot of other button combinations that I sometimes accidentally pressed and some cool things happen (image attached) but don’t know what they are. May be extend the list of explained commands?

<img width="571" alt="87338329-aa632780-c54d-11ea-9242-3d82f53185d1" src="https://user-images.githubusercontent.com/9891700/87417382-fce12a00-c5c7-11ea-99e9-841f668c648f.png">

**Comment by OrodRazeghi** [comment]
The only other keyboard shortcuts that are available but not listed in the clipper renderer window are: W and S keys for wireframe and surface representation. As these two shortcuts do not help much with the processes of clipping pipeline, it is better not to list them explicitly and keep the renderer window less cluttered.
