### ISSUE TITLE
App crashes unexpectedly 

### ISSUE THREAD

**Issue by charlessillett** [CemrgAppDevelopers/CemrgApp#28]
The app crashes unexpectedly after loading a segmentation in the Scar Quantification pipeline. 
When I reboot, the app then suffers badly from lag as I try to move the cursor - this issue wasn't present before the crash.

**Comment by alonsoJASL** [comment]
Hi @charlessillett , we need more info about this. 

To be quicker, I recommend you copy and fill the [issue template form](https://github.com/CemrgAppDevelopers/CemrgApp/wiki/ISSUE_TEMPLATE.md). 

If you need more info on bugs, also check our [Reporting bugs page](https://github.com/CemrgAppDevelopers/CemrgApp/wiki/Reporting-bugs).

**Comment by charlessillett** [comment]
### Prerequisites

Put an X between the brackets (without spaces [X]) on the following lines if you have done all of the following:

* [X] Checked the wiki board for common solutions: <https://github.com/CemrgAppDevelopers/CemrgApp/wiki>
* [X] Checked that your issue isn't already filed: <https://github.com/search?q=+is%3Aissue+user%3ACemrgAppDevelopers>
* [] Are you providing the log? <https://github.com/CemrgAppDevelopers/CemrgApp/wiki/Troubleshooting>

### Description

 Describe the issue

### Steps to Reproduce

Steps is either one of the following (can't remember exact steps unfortunately)

1. Selected Window -> Open Perspective -> Cemrg Scar Quantification 
2. Uploaded CT image in nii format by selecting Open File 

OR

1. Selected Window -> Open Perspective -> Cemrg Scar Quantification 
2. Uploaded CT image in nii format by selecting Open File 
3. Selected Advanced Analysis in Scar Quantification Pipeline
4. Selected Segment in Scar Quantification Pipeline
5. Selected segmentation in nii format.

**Expected behaviour:**

Load CT image

OR 

Load segmentation onto the loaded CT image.

**Actual behavior:**

CemrgApp closes.

**Reproduces how often:**

Does not reproduce.

What percentage of the time does it reproduce? 

Hard to say but rarely. Less than 10%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue. 
´´´

**Comment by OrodRazeghi** [comment]
The lag issue can be fixed by clearing the application's cache using the following command from the terminal:

`./CemrgApp --BlueBerry.clean`

The crash issue is very similar to the reported issue #29, which remains open and under review at the moment.
