### ISSUE TITLE
[CICD] Script to generate CemrgApp packages automatically in linux (Ubuntu 18.04).

### ISSUE THREAD

**Issue by alonsoJASL** [CemrgAppDevelopers/CemrgApp#34]
+ Create a script to build CemrgApp automatically in linux
+ Include MIRTK and meshtools3D libraries (MLib, M3DLib)

**Comment by ericspod** [comment]
We can reduce the stored package size by deleting unneeded directories like `.git`, `doc`, `test`, etc. There needs to be some investigation in the package to find what directories we don't need.
