### ISSUE TITLE
Regularising Directory Structure in Packaged Apps

### ISSUE THREAD

**Issue by ericspod** [CemrgAppDevelopers/CemrgApp#38]
We want to package other executables with the application. The idea is to put these in the same directory as the main executable and be able to find their paths within the app. The app must thus be able to identify what directory its executable lives in and use that to find the others, perhaps using Qt's library for cross-platform compatibility. These files will have to be added to the macOS .app structure.

**Comment by OrodRazeghi** [comment]
This is the class where the app calls other executables (MIRTK, M3D) and Docker Containers within the code: [Cemrg Command Line](https://github.com/CemrgDevelopers/CemrgApp/blob/development/CemrgApp/Modules/CemrgAppModule/src/CemrgCommandLine.cpp)
