### ISSUE TITLE
Remove Docker Invocation from Module

### ISSUE THREAD

**Issue by ericspod** [CemrgAppDevelopers/CemrgApp#50]
Docker is used for access MIRTK, a neural network, CGAL, and OpenCARP. This is hard coded in the command line module. To be able to dockerize CemrgApp this needs to be removed and replaced with included binaries or composed with running Docker images.

First priority is removing MIRTK invocation and use internal build version.

**Comment by alonsoJASL** [comment]
Our other priorities do not allow us to dockerise CemrgApp at the moment. We will reconsider this when we have developer resources.
