### ISSUE TITLE
MITK compilation error (Ubuntu) from DCMTK 

### ISSUE THREAD

**Issue by sverdlab** [CemrgAppDevelopers/CemrgApp#69]
hi I followed the instructions - but i got this error on Ubuntu: 
[  4%] Building CXX object ofstd/tests/CMakeFiles/ofstd_tests.dir/tvariant.cc.o
[  4%] Linking CXX executable ../../bin/ofstd_tests
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_setFromUCallBack_60'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_open_60'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_getName_60'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_TO_U_CALLBACK_STOP_60'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_TO_U_CALLBACK_SKIP_60'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_FROM_U_CALLBACK_SKIP_60'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_getFromUCallBack_60'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_FROM_U_CALLBACK_STOP_60'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_convertEx_60'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_setToUCallBack_60'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_close_60'
../../lib/libofstd.so.3.6.3: undefined reference to `u_errorName_60'
collect2: error: ld returned 1 exit status
ofstd/tests/CMakeFiles/ofstd_tests.dir/build.make:450: recipe for target 'bin/ofstd_tests' failed
make[6]: *** [bin/ofstd_tests] Error 1
CMakeFiles/Makefile2:2350: recipe for target 'ofstd/tests/CMakeFiles/ofstd_tests.dir/all' failed
make[5]: *** [ofstd/tests/CMakeFiles/ofstd_tests.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/DCMTK.dir/build.make:133: recipe for target 'ep/src/DCMTK-stamp/DCMTK-build' failed
make[3]: *** [ep/src/DCMTK-stamp/DCMTK-build] Error 2
CMakeFiles/Makefile2:346: recipe for target 'CMakeFiles/DCMTK.dir/all' failed
make[2]: *** [CMakeFiles/DCMTK.dir/all] Error 2

**Comment by alonsoJASL** [comment]
Hello, without knowing the version of ubuntu, I can recognise your error.  I added a few lines on the [Compilation Tips Page](https://github.com/OpenHeartDevelopers/CemrgApp/wiki/Compilation-Tips#ubuntu-compilation-tips) of our wiki, which I will repeat below. 

Make sure you have the following installed:  `apt-get install libxss1 libnspr4 libnss3` .  Also, check the `DCMTK-Build` folder on cmake located on your `$CEMRG_BUILD/ep/src/DCMTK-Build`. Make sure the following variables are set as shown: 

+ `DCMTK_ENABLE_CHARSET_CONVERSION=stdlibc (iconv)`
+ `DCMTK_WITH_ICU=OFF`

Finally, when submitting an issue, please try to stick to our [Reporting Bugs Guidelines](https://github.com/OpenHeartDevelopers/CemrgApp/wiki/Reporting-bugs) and using the [ISSUE TEMPLATE](https://github.com/OpenHeartDevelopers/CemrgApp/wiki/ISSUE_TEMPLATE.md). 

Closing unless problems persist. We can reopen it if necessary.
