### ISSUE TITLE
[macOS] CemrgApp crashes when turning on 3D interpolation

### ISSUE THREAD

**Issue by alonsoJASL** [CemrgAppDevelopers/CemrgApp#7]
Program crashes and exits when turning on 3D interpolation when segmenting. The error does not occur if 3D interpolation is turned on **before** starting the segmentation.

### Information 
**Plugin**: Scar
**Step 4**: Segment Images (manual option)

**Comment by alonsoJASL** [comment]
**Workaround:** if the user enabled 3D interpolation before start segmenting, then the problem does not occur.

**Comment by OrodRazeghi** [comment]
I can't reproduce this on macOS or Linux versions.

**Comment by alonsoJASL** [comment]
Closing this for now as it does not seem to still be a problem. Reopen if it resurfaces.
